services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "url_shortener"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data

volumes:
  pg_volume:
